############ Experimental Settings ############
fps: 50          # camera frame rate (units: frames/sec)
# camera_scale: 60 # pixel/cm
input_data_path: "data/ant_field_final_filtered"
result_path: "results/ant_antennae"
GPU_project_path: "/rapids/notebooks/host/BM_GPU"

########### Skeleton ############
skeleton: [
    [0,1],[1,2],[2,3],
    [4,5],[5,6],[6,7],
    [8,9],[9,10],
    [11,12],[12,13],
    [14,15],[15,16],
    [17,18],[18,19],[19,20],
    [21,22],[22,23],
    [24,25],[25,26],
    [27,28],[28,29]
]
skeleton_color: [
    'tab:blue','tab:blue','tab:blue',
    'tab:orange','tab:orange','tab:orange',
    'tab:green','tab:green',
    'tab:red','tab:red',
    'tab:purple','tab:purple',
    'tab:brown','tab:brown','tab:brown',
    'tab:pink','tab:pink',
    'tab:gray','tab:gray',
    'tab:olive','tab:olive']
skeleton_fill: []
likelihood_thresh: 0.8
marker_thresh: 1
bad_fr_pad: 100
########### Signals ############
bp_center: 2
bp_scale: [1, 2]
bp_rotate: 1
scale: False # int

########### Postural Features ############
# Marker Position
markers: [0,1,3, 5,6,7, 8,9, 11,12, 14,15, 18,19,20, 21,22, 24,25, 27,28] # This does not do anything right now
marker_kinematic_pca_components: 170
marker_labels: [head, thorax, abdomen, 
(R) Antennae Tip, (R) Antennae Mid, (R) Antennae Base,
(R) FL Tip, (R) FL Mid, (R) ML Tip, (R) ML Mid, (R) HL Tip, (R) HL Mid,
(L) Antennae Tip, (L) Antennae Mid, (L) Antennae Base,
(L) FL Tip, (L) FL Mid, (L) ML Tip, (L) ML Mid, (L) HL Tip, (L) HL Mid]

# Joint Angle ("method": 0 applies for angles ranging from -180 to 180, and "method":1 is 0-360)
angle_kinematic_pca_components: 70
angles:
  # (R) ANTENNAE
  - {"a": 5, "b": 6, "c": 0, "method": 0}
  # (R) ANTENNAE 2
  - {"a": 6, "b": 0, "c": 1, "method": 0}
  # (L) ANTENNAE
  - {"a": 18, "b": 19, "c": 0, "method": 0}
  # (L) ANTENNAE 2
  - {"a": 19, "b": 0, "c": 1, "method": 0}
  # HEAD
  - {"a": 0, "b": 1, "c": 2, "method": 0}

# Doesn't matter for pipeline but creates labels on figures.
angle_labels:
  - (R) Antennae
  - (R) Antennae 2 
  - (L) Antennae 
  - (L) Antennae 2
  - HEAD

# Limb Length
limb_kinematic_pca_components: 70
limbs:
  - [5,6]
  - [6,0]
  - [18,19]
  - [19,0]
  - [0,1]
  - [1,2]
limb_labels:
  - (R) Antennae Mid-Tip
  - (R) Antennae Base-Mid
  - (L) Antennae Mid-Tip
  - (L) Antennae Base-Mid
  - Head
  - Abdomen


include_marker_postural: False
include_marker_kinematic: False

include_angle_postural: False
include_angle_kinematic: False

include_limb_postural: False
include_limb_kinematic: False

include_all_postural: True
include_all_kinematic: True
include_all_features: True

########### Morlet Wavelet Transformation ###########
w: 5
f_bin: 20       # number of frequency bin
f_min: 1
period_max: 1    # unit: s
period_min: 0.04  # unit: s ; cannot be lower than 2/fps

########### UMAP ###########
n_components: 2
n_neighbors: 40
n_epochs: 20000 
min_dist: 0.001
spread: 1.0 # 3.0
negative_sample_rate: 5
init: "spectral"
repulsion_strength: 1.0 # 10

########### Clustering ###########

########### Figures ###########
raw_video_path: "/rapids/notebooks/host/Ant_Videos/ant_field"
save_video_path: "videos/final"
num_sample_videos: 9
max_video_length: 100
video_type: 0

########### Save Path ###########
save_bodypoints: True
save_scaled_bodypoints: True
save_body_orientation_angles: False
save_rotated_bodypoints: True
save_embeddings: True
save_clusters: True
